// File generated by FlutterFire CLI (run: dart run flutterfire_cli:flutterfire configure).
// Replace this file by running the command above so it contains your project's config.
//
// Until then, this placeholder allows the app to compile. Auth will fail until
// you add a Firebase project and run `dart run flutterfire_cli:flutterfire configure`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Placeholder Firebase options. Run `dart run flutterfire_cli:flutterfire configure`
/// to generate options for your Firebase project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'PLACEHOLDER_RUN_FLUTTERFIRE_CONFIGURE',
      appId: '1:000000000000:android:0000000000000000000000',
      messagingSenderId: '000000000000',
      projectId: 'your-project-id',
      authDomain: 'your-project-id.firebaseapp.com',
      storageBucket: 'your-project-id.appspot.com',
    );
  }
}
